"""
配置常量
"""

# 测试模式：只加载一个 TPS 文件，加快启动速度
TEST_MODE = True

# 帧索引常量
FRAME_INDEX_MAGIC = 0x4C3D2E1F
FRAME_INDEX_SIZE = 44
INDEX_REGION_START = 0xF900000
FRAME_INDEX_OFFSET = 0x28  # 索引头部偏移

# 通道定义
CHANNEL_VIDEO_CH1 = 2
CHANNEL_AUDIO = 3
CHANNEL_VIDEO_CH2 = 258
VALID_CHANNELS = (CHANNEL_VIDEO_CH1, CHANNEL_AUDIO, CHANNEL_VIDEO_CH2)

# 帧类型
FRAME_TYPE_I = 1
FRAME_TYPE_P = 3

# 服务器配置
DEFAULT_DVR_PATH = "/Volumes/NO NAME"
DEFAULT_TIMEZONE = "Asia/Shanghai"
HOST = "0.0.0.0"
PORT = 8152

# 音频配置
AUDIO_SAMPLE_RATE = 8000
AUDIO_FRAME_DURATION_MS = 160  # 每帧 160ms

# 视频配置
VIDEO_FPS = 25
VIDEO_FRAME_INTERVAL = 1.0 / VIDEO_FPS
